# Generated by Django 2.0 on 2020-06-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0036_tour_operator_u_pswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Starting_Date',
            field=models.DateField(default=0),
        ),
    ]
