# Generated by Django 2.0 on 2020-06-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0038_auto_20200609_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='Starting_Date',
        ),
    ]
