# Generated by Django 2.0 on 2020-01-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20200102_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='event_host',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='revs',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='required_gear',
            name='req',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serv',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='acts',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='event_host',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='reqs',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='revs',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='sers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Destinations',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Required_Gear',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Tour_Operator',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
