# Generated by Django 2.0 on 2020-01-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_auto_20200102_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
