# Generated by Django 2.0 on 2020-01-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Frontend', '0010_auto_20200102_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.PositiveIntegerField(default=0)),
                ('act1', models.CharField(default='-', max_length=200)),
                ('act2', models.CharField(default='-', max_length=200)),
                ('act3', models.CharField(default='-', max_length=200)),
                ('act4', models.CharField(default='-', max_length=200)),
                ('act5', models.CharField(default='-', max_length=200)),
                ('act6', models.CharField(default='-', max_length=200)),
                ('act7', models.CharField(default='-', max_length=200)),
                ('act8', models.CharField(default='-', max_length=200)),
                ('act9', models.CharField(default='-', max_length=200)),
                ('act10', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des_Id', models.SlugField(default=0, max_length=150, unique=True)),
                ('Des_Name', models.CharField(max_length=200)),
                ('Des_Description1', models.CharField(max_length=2000)),
                ('state', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=200)),
                ('Languages', models.CharField(max_length=200)),
                ('history1', models.CharField(max_length=200)),
                ('history2', models.CharField(max_length=200)),
                ('history3', models.CharField(max_length=200)),
                ('Des_H1', models.CharField(max_length=200)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.PositiveIntegerField(default=0)),
                ('img1', models.FileField(null=True, upload_to='Trip/', verbose_name='')),
                ('img2', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img3', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img4', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img5', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img6', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img7', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img8', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img9', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
                ('img10', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Required_Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_id', models.PositiveIntegerField(default=0)),
                ('req1', models.CharField(default='-', max_length=200)),
                ('req2', models.CharField(default='-', max_length=200)),
                ('req3', models.CharField(default='-', max_length=200)),
                ('req4', models.CharField(default='-', max_length=200)),
                ('req5', models.CharField(default='-', max_length=200)),
                ('req6', models.CharField(default='-', max_length=200)),
                ('req7', models.CharField(default='-', max_length=200)),
                ('req8', models.CharField(default='-', max_length=200)),
                ('req9', models.CharField(default='-', max_length=200)),
                ('req10', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rev_Id', models.SlugField(default=0, max_length=150, unique=True)),
                ('reviewFor', models.CharField(max_length=200)),
                ('reviewBy', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rev_good', models.CharField(default='-', max_length=5000)),
                ('rev_bad', models.CharField(default='-', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField(default=0)),
                ('ser1', models.CharField(default='-', max_length=200)),
                ('ser2', models.CharField(default='-', max_length=200)),
                ('ser3', models.CharField(default='-', max_length=200)),
                ('ser4', models.CharField(default='-', max_length=200)),
                ('ser5', models.CharField(default='-', max_length=200)),
                ('ser6', models.CharField(default='-', max_length=200)),
                ('ser7', models.CharField(default='-', max_length=200)),
                ('ser8', models.CharField(default='-', max_length=200)),
                ('ser9', models.CharField(default='-', max_length=200)),
                ('ser10', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Op_Id', models.SlugField(default=0, max_length=150, unique=True)),
                ('Op_Name', models.CharField(max_length=100)),
                ('Op_phone', models.CharField(default=0, max_length=11)),
                ('Op_email', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Id', models.SlugField(default=0, max_length=150, unique=True)),
                ('T_Name', models.CharField(max_length=200)),
                ('noOfDays', models.PositiveIntegerField(default=0)),
                ('noOfNights', models.PositiveIntegerField(default=0)),
                ('display', models.BooleanField(default=False)),
                ('Dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.Destinations')),
                ('acts', models.ManyToManyField(blank=True, to='Frontend.Activities')),
                ('event_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.Tour_Operator')),
                ('imgs', models.ManyToManyField(blank=True, to='Frontend.Images')),
                ('reqs', models.ManyToManyField(blank=True, to='Frontend.Required_Gear')),
                ('revs', models.ManyToManyField(blank=True, to='Frontend.Review')),
                ('sers', models.ManyToManyField(blank=True, to='Frontend.Services')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Name', models.CharField(max_length=100)),
                ('U_pswd', models.CharField(max_length=30)),
                ('U_email', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='Frontend.Images'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='revs',
            field=models.ManyToManyField(blank=True, to='Frontend.Review'),
        ),
    ]
