# Generated by Django 2.0 on 2020-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_auto_20200102_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pic',
            field=models.FileField(blank=True, upload_to='Trip/', verbose_name=''),
        ),
    ]
