# Generated by Django 2.0 on 2020-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_trip_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='startLocation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
