# Generated by Django 2.0 on 2020-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_auto_20200102_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='startDate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
