# Generated by Django 2.0 on 2020-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_auto_20200102_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_Id', models.SlugField(default=0, max_length=150, unique=True)),
                ('deal_Name', models.CharField(max_length=200)),
                ('pic', models.FileField(blank=True, upload_to='Trip/', verbose_name='')),
            ],
        ),
    ]
