# Generated by Django 2.0 on 2020-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
    ]
