# Generated by Django 2.0 on 2020-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0019_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='Source',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='Title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='date',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='description',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
