# Generated by Django 2.0 on 2020-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0020_auto_20200407_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Sraping_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url_title', models.CharField(default=0, max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips_Operators_Sraping_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url_title', models.CharField(default=0, max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips_Sraping_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url_title', models.CharField(default=0, max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
