# Generated by Django 2.0 on 2020-04-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0022_trip_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Rev_Id',
        ),
    ]
