# Generated by Django 2.0 on 2020-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0024_auto_20200518_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
