# Generated by Django 2.0 on 2020-05-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0027_auto_20200520_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Discount_Price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='Item_Is_Discount',
            field=models.BooleanField(default=False),
        ),
    ]
