# Generated by Django 2.0 on 2020-05-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0028_auto_20200520_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='items',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items_in_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items_in_cart',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Frontend.Trip'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_in_order',
        ),
        migrations.AddField(
            model_name='order',
            name='items_in_order',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Frontend.Trip'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
