# Generated by Django 2.0 on 2020-06-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0029_auto_20200531_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='C_City',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='C_PH',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
