# Generated by Django 2.0 on 2020-06-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0030_auto_20200601_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='C_City',
            new_name='U_City',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='C_PH',
            new_name='U_PH',
        ),
    ]
