# Generated by Django 2.0 on 2020-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0033_auto_20200601_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='O_PH',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='No_of_Seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
