# Generated by Django 2.0 on 2020-06-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0034_auto_20200602_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_in_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.Trip'),
        ),
    ]
