# Generated by Django 2.0 on 2020-06-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0036_tour_operator_u_pswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_operator',
            name='U_pswd',
            field=models.CharField(max_length=30),
        ),
    ]
