# Generated by Django 2.0 on 2020-06-08 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0038_trip_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Departure_Date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
