# Generated by Django 2.0 on 2020-06-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0041_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Total_Rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
