# Generated by Django 2.0 on 2020-06-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0042_trip_total_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestincationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewFor', models.CharField(max_length=200)),
                ('reviewBy', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rev_good', models.CharField(default='-', max_length=5000)),
                ('rev_bad', models.CharField(default='-', max_length=5000)),
                ('approved', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TourCompanyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewFor', models.CharField(max_length=200)),
                ('reviewBy', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rev_good', models.CharField(default='-', max_length=5000)),
                ('rev_bad', models.CharField(default='-', max_length=5000)),
                ('approved', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewFor', models.CharField(max_length=200)),
                ('reviewBy', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rev_good', models.CharField(default='-', max_length=5000)),
                ('rev_bad', models.CharField(default='-', max_length=5000)),
                ('approved', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='Op_rating',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='Op_review',
        ),
        migrations.RemoveField(
            model_name='tour_operator',
            name='Op_rating',
        ),
        migrations.RemoveField(
            model_name='tour_operator',
            name='Op_review',
        ),
        migrations.AddField(
            model_name='destinations',
            name='Average_Rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destinations',
            name='Total_Rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinations',
            name='Total_Reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour_operator',
            name='Average_Rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tour_operator',
            name='Total_Rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour_operator',
            name='Total_Reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='revs',
            field=models.ManyToManyField(blank=True, to='Frontend.DestincationReview'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='revs',
            field=models.ManyToManyField(blank=True, to='Frontend.TripReview'),
        ),
        migrations.AddField(
            model_name='tour_operator',
            name='revs',
            field=models.ManyToManyField(blank=True, to='Frontend.TourCompanyReview'),
        ),
    ]
