# Generated by Django 2.0 on 2020-06-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0043_auto_20200610_0411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
