# Generated by Django 2.0 on 2020-06-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0046_tripscrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripscrap',
            name='Average_Rating',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Departure_Date',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Dest',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Discount_Price',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Item_Is_Discount',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='No_of_Seats',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Total_Rating',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Total_Reviews',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='Trip_Id',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='acts',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='event_host',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='reqs',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='revs',
        ),
        migrations.RemoveField(
            model_name='tripscrap',
            name='sers',
        ),
    ]
