# Generated by Django 2.0 on 2020-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0047_auto_20200611_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscrap',
            name='pic',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tripscrap',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
