# Generated by Django 2.0 on 2020-06-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0048_auto_20200611_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_Claimed',
            new_name='Order_Booked',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_Packed',
            new_name='Payment_Received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_shipped',
        ),
    ]
