# Generated by Django 2.0 on 2020-06-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0039_trip_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='Departure_Date',
        ),
    ]
