# Generated by Django 2.0 on 2020-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0040_remove_trip_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Departure_Date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
